easy_admin:
    entities:
        Contact:
            class: App\Entity\Contact
        Skill:
            class: App\Entity\Team\Skill
        Certification:
            class: App\Entity\Team\Certification
        Reference:
            class: App\Entity\Team\Reference
        Team:
            class: App\Entity\Team
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                 fields:
                    - 'firstName'
                    - 'lastName'
                    - 'experience'
                    - 'jobTitle'
                    - 'skills'
                    - 'certifications'
                    - 'references'
                    - 'twitter'
                    - 'linkedin'
                    - 'github'
                    - { property: 'pictureFile', type: 'vich_image' }